### ISSUE TITLE
너비 우선 탐색 (BFS) / 깊이 우선 탐색 (DFS)

### ISSUE THREAD

**Issue by joonyle99** [BRIDGE-DEV/BRIDGE_Algorithm#14]
데이터를 탐색할 때 깊이와 너비 중 무엇을 더 우선으로 탐색을 하는지에 대한 완전 탐색 알고리즘인 BFS와 DFS에 대해 최근에 공부한 바가 있습니다. 이번에는 개념적으로는 간단하게 복기하고 한 문제를 고른 후, BFS와 DFS 중 어느 알고리즘으로 풀어야 하는지와 문제풀이 그 과정을 중점으로 공부하겠습니다.

**Comment by fkdl0048** [comment]
오.. 기대됩니다!
