### ISSUE TITLE
NearthYou: A* 알고리즘

### ISSUE THREAD

**Issue by NearthYou** [BRIDGE-DEV/BRIDGE_Algorithm#6]
게임의 이동 시스템을 만들며 사용했던 A*알고리즘에 대해 정확한 이해가 필요할 것 같아 선정해봤습니다.

**Comment by joonyle99** [comment]
A* ㄷㄷ 고수군요

**Comment by NearthYou** [comment]
아 면접 때 게임 만들면서 사용해봤던 알고리즘에 대해서 많이 여쭤보시는 것 같더라구요.
저도 A* 사용했을 당시 이 곳 저 곳에서 긁어와서 대충 이해 없이 만들었던 터라, 이번 기회에 공부해보려고 합니다..!

**Comment by joonyle99** [comment]
화이팅입니다..!

**Comment by fkdl0048** [comment]
도전하는 모습 본 받겠습니다.
